name: Nodejs CI
on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: trivy filesystem scan
          uses: aquasecurity/trivy-action@v0.33.1
          with:
                scan-type: filesystem
                scan-path: .
                format: 'table'
                exit-code: '1'
                severity: 'CRITICAL,HIGH'
                ignore-unfixed: true

        - name: build docker image
          uses: docker/build-push-action@v6
          with:
                context: .
                push: false
                tags: my-nodejs-app:latest
        
        - name: trivy image scan
          uses: aquasecurity/trivy-action@v0.33.1
          with:
                scan-type: image
                image-ref: my-nodejs-app:latest
                format: 'table'
                exit-code: '1'
                severity: 'CRITICAL,HIGH'
                ignore-unfixed: true

        - name: start docker compose
          uses: hoverkraft-tech/compose-action@05da55b2bb8a5a759d1c4732095044bd9018c050 # v2.4.3
          with:
                compose-file: docker-compose.yml
                up-flags: "--build -d"

        - name: Verify application is running
          run: |
                sleep 5
                docker compose ps
                curl -f http://localhost:3000 || exit 1
                echo "Application is running successfully"
        

    