name: Nodejs CI
on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: build docker image
          uses: docker/build-push-action@v6
          with:
                context: .
                push: false
                tags: my-nodejs-app:latest

        - name: set up docker compose
          uses: docker/setup-compose-action@v1
          with:
                compose-file: docker-compose.yml
        
        - name: run docker compose
          run: |
            docker-compose up --build -d
            sleep 10  # wait for the app to start
            docker-compose ps

            #test if the app is running
            curl -f http://localhost:3000 || exit 1

            echo "App is running successfully"
        

    